server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  application:
    name: boot-001

users:
   users:
    jovidio: "123456"
    nmartinez: "123456"
    jrivera5: "Pdv#001"
    ccartagena33057: "Pdv#001"

utilities:
  concesionario: "SJ2124"
  licence: "4879680"
#  licence: "7006169"
  mode: "prod"
  baseUrl: "https://pdvprod-preprod-b5brcya4eggkghc0.eastus-01.azurewebsites.net"
  loginUrl: "/Forms/Account/LoginNew.aspx"
  homeUrl: "/Default.aspx"
  preventaUrl: "/Forms/CarPartialRegistrationBatch.aspx"
  pdfRoute: "C:/Users/jgraph/Documents/JAVA/AutoRegLoadBot/utilities/pdfPrueva.pdf"
  ciclo: 1
  concurrency: 1
  waitTimeOut: 60
  vinBanckRoute: "C:/Users/jgraph/Documents/JAVA/AutoRegLoadBot/utilities/Vins.txt"
elements:

  registrationVinImput: "MainContent_ucCarRegistration_txtVIN"
  usernameInput: "LoginUser_UserName"
  passwordInput: "LoginUser_Password"
  vinInput: "MainContent_txtVIN"
  plateInput: "MainContent_txtPlateNumber"
  yearInput: "MainContent_txtYear"
  makeInput: "MainContent_txtMake"
  modelInput: "MainContent_txtModel"
  registrationDoorInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtDoors"
  registrationCilinInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtCylinder"
  registrationPowerInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtAutoHorseForce"
  registrationDealerLicenceInput: "MainContent_ucCarRegistration_ucGeneralInfo_txtLicense"
  registrationPlateInput: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtPlateNumber"
  registrationTagInput: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtRegistrationSticker"
  registrationContractInput: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtContractNumber"
  registrationContributoryPriceInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtContributoryPrice"
  registrationArbitragePriceInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtExciseTaxesPaid"
  contractNumberInput: "MainContent_contracNumber"
  registrationTagDateSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtValidityDateFrom"
  licenceInput: "MainContent_txtLicenseNumber"
  registrationLicenceInput: "MainContent_ucCarRegistration_txtLicenseNumber"
  registrationYearInput: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtYear"
  registrationMakeInput: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtMake"
  registrationModelInput: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtModel"
  registrationBuyType: "MainContent_ucCarRegistration_ddlCategory"
  registrationBuyTypeValue: "1"
  registrationSalePrice: "ctl00_MainContent_ucCarRegistration_txtSalePrice"
  registrationDataUserConfirmButton: "MainContent_ucCarRegistration_btnConfirmationOwner"
  registrationYes: "MainContent_ucCarRegistration_mbMessage_btnOK"
  saleDateInput: "MainContent_SaleDate"
  reimbursementDateInput: "MainContent_DisbursementDate"
  registrationOrigenSaleDateSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtTitleSaleDate"
  dealerLicenceInput: "MainContent_txtLicense"
  concessionaryName: "MainContent_txtConcesionarioName"
  dealerLicenseDate: "MainContent_txtLicenseDate"
  dateUserConfirmation: "MainContent_btnConfirmationOwner"
  fileInputCssSelector: "input[type='file']"
  fileNameCellXpath: "//td[normalize-space(text()) != '']"
  registrationPayDateSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtRecievedDate"
  registrationSelleDateSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtEventDate"
  subTypeSelect: "MainContent_ddlMySubType"
  subTypeRegisterValue: "16"
  registrationOrigenType: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_ddlTitle"
  registrationOrigenTittleValue: "2"
  colorSelect: "MainContent_ddlColor1"
  registrationColorSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_ddlColor1"
  registrationOdometer: "ctl00_MainContent_ucCarRegistration_ucVehicleRegistryInfo_txtOdometer"
  registrationCarTypeSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_ddlVehicleType"
  registrationCarTypeValue: "5"
  registrationCarUseTypeSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_ddlVehicleUseType"
  registrationCarUseTypeValue: "1"
  registrationCarPropurtionTypeSelect: "MainContent_ucCarRegistration_ucVehicleRegistryInfo_ddlVehiclePropulsionType"
  registrationCarPropurtionTypeValue: "1"

  SubmitLoginButton: "iniciar-sesin-1"
  termConditionButton1: "ucTermsConditions_gvTermConditionsBullets_chkChecked_0"
  termConditionButton2: "ucTermsConditions_gvTermConditionsBullets_chkChecked_1"
  termConditionButton3: "ucTermsConditions_gvTermConditionsBullets_chkChecked_2"
  termConditionButton4: "ucTermsConditions_gvTermConditionsBullets_chkChecked_3"
  termConditionConfirmButton: "ucTermsConditions_btnSubmit"
  preSaleButton: "MainContent_navMenu_btnCarPartialRegistration"
  registerButton: "MainContent_navMenu_ibtndivRegistrosBatch"
  vinSerchButton: "MainContent_BtnSearchVIN"
  dealerLicenseSerchButton: "MainContent_BtnSearchLicense"
  registrationSerchLicenceButton: "MainContent_ucCarRegistration_ucGeneralInfo_BtnSearchLicense"
  registrationConcessionaryName: "MainContent_ucCarRegistration_ucGeneralInfo_txtConcepcionarioName"
  registrationLicenceDateInput: "MainContent_ucCarRegistration_ucGeneralInfo_txtLicenseDate"
  digitalCheckButton1: "MainContent_chkConfirmation"
  digitalCheckButton2: "MainContent_CheckBox1"
  registrationDigitalCheckButton1: "MainContent_ucCarRegistration_chkConfirmation"
  registrationDigitalCheckButton2: "MainContent_ucCarRegistration_CheckBox1"
  fileButtonCssSelector: "input.ruButton.ruBrowse"
  continueButton: "PageFunctionsContent_ucRightFunctionBox_lvwFunctions_imbFunction_0"
  tryAgainButton: "MainContent_btnYes"

driver:
   path: "C:/Users/jgraph/Documents/JAVA/AutoRegLoadBot/utilities/msedgedriver.exe"

logging:
  level:
    root: INFO
    com.TestBoot.boot_001: DEBUG
    org.springframework.boot.web.embedded.tomcat.GracefulShutdown: ERROR
    org.springframework.beans.factory.support.DisposableBeanAdapter: ERROR
    org.openqa.selenium: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%15.15t]){faint} %clr(%-5level) %clr(%logger{39}){cyan} : %msg%n"
  group:
    boot001: com.TestBoot.boot_001
  levelpattern:
    boot001: "%clr(%-5level){%level_color}: %msg%n"