server:
  port: 8082
spring:
  output:
    ansi:
      enabled: always
  application:
    name: boot-001
users:
  users:
    jovidio: "123456"
    nmartinez: "123456"
    jrivera5: "Pdv#001"
    ccartagena33057: "Pdv#001"
utilities:
  concesionario: "SJ2124"
  licence: "7006169"
  baseUrl: "https://pdvprod-preprod.azurewebsites.net/"
  loginUrl: "Forms/Account/LoginNew.aspx"
  homeUrl: "Default.aspx"
  preventaUrl: "Forms/CarPartialRegistrationBatch.aspx"
  pdfRoute: "/app/utilities/pdfPrueva.pdf"
  vinBanckRoute: "/app/utilities/Vins.txt"
  ciclo: 200
  concurrency: 25
  waitTimeOut: 30
elements:
  usernameInput: "LoginUser_UserName"
  passwordInput: "LoginUser_Password"
  vinInput: "MainContent_txtVIN"
  plateInput: "MainContent_txtPlateNumber"
  yearInput: "MainContent_txtYear"
  makeInput: "MainContent_txtMake"
  modelInput: "MainContent_txtModel"
  contractNumberInput: "MainContent_contracNumber"
  licenceInput: "MainContent_txtLicenseNumber"
  saleDateInput: "MainContent_SaleDate"
  reimbursementDateInput: "MainContent_DisbursementDate"
  dealerLicenceInput: "MainContent_txtLicense"
  concessionaryName: "MainContent_txtConcesionarioName"
  dealerLicenseDate: "MainContent_txtLicenseDate"
  dateUserConfirmation: "MainContent_btnConfirmationOwner"
  fileInputCssSelector: "input[type='file']"
  fileNameCellXpath: "//td[normalize-space(text()) != '']"
  subTypeSelect: "MainContent_ddlMySubType"
  subTypeRegisterValue: "16"
  colorSelect: "MainContent_ddlColor1"
  SubmitLoginButton: "iniciar-sesin-1"
  termConditionButton1: "ucTermsConditions_gvTermConditionsBullets_chkChecked_0"
  termConditionButton2: "ucTermsConditions_gvTermConditionsBullets_chkChecked_1"
  termConditionButton3: "ucTermsConditions_gvTermConditionsBullets_chkChecked_2"
  termConditionButton4: "ucTermsConditions_gvTermConditionsBullets_chkChecked_3"
  termConditionConfirmButton: "ucTermsConditions_btnSubmit"
  preSaleButton: "MainContent_navMenu_btnCarPartialRegistration"
  vinSerchButton: "MainContent_BtnSearchVIN"
  dealerLicenseSerchButton: "MainContent_BtnSearchLicense"
  digitalCheckButton1: "MainContent_chkConfirmation"
  digitalCheckButton2: "MainContent_CheckBox1"
  fileButtonCssSelector: "input.ruButton.ruBrowse"
  continueButton: "PageFunctionsContent_ucRightFunctionBox_lvwFunctions_imbFunction_0"
  tryAgainButton: "MainContent_btnYes"
chrome:
  driver:
    path: "/app/utilities/ChromeDriver/chromedriver"
logging:
  level:
    root: INFO
    com.TestBoot.boot_001: DEBUG
    org.springframework.boot.web.embedded.tomcat.GracefulShutdown: ERROR
    org.springframework.beans.factory.support.DisposableBeanAdapter: ERROR
    org.openqa.selenium: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%15.15t]){faint} %clr(%-5level) %clr(%logger{39}){cyan} : %msg%n"
  group:
    boot001: com.TestBoot.boot_001
  levelpattern:
    boot001: "%clr(%-5level){%level_color}: %msg%n"
