server:
  port: 8082
spring:
  output:
    ansi:
      enabled: always
  application:
    name: boot-001
utilities:
  user1: "jovidio"
  user2: "nmartinez"
  user3: "jrivera5"
  password1: "123456"
  password2: "123456"
  password3: "pdv#001"
  concesionario: "SJ2124"
  licence: "7006169"
  baseUrl: "https://testwaf.portaldevehiculos.com/"
  loginUrl: "Forms/Account/LoginNew.aspx"
  homeUrl: "Default.aspx"
  preventaUrl: "Forms/CarPartialRegistrationBatch.aspx"
  pdfRoute: "C:/Users/jgraph/Documents/JAVA/boot-001/pdfPrueva.pdf"
  ciclo: "300"
  usersActives: "1"
  waitTimeOut: "60"
  GeneratorVinkey: "rRnChorlYRs0ivczHyvjCQ==7zWRkgEyxSpfiBlr"
chrome:
  driver:
    path: "C:/Users/jgraph/Documents/JAVA/boot-001/chromedriver-win64/chromedriver.exe"
    api:
      ninjas:

logging:
  level:
    root: INFO
    com.TestBoot.boot_001: DEBUG
    org.springframework.boot.web.embedded.tomcat.GracefulShutdown: ERROR
    org.springframework.beans.factory.support.DisposableBeanAdapter: ERROR
    org.openqa.selenium: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%15.15t]){faint} %clr(%-5level) %clr(%logger{39}){cyan} : %msg%n"
  group:
    boot001: com.TestBoot.boot_001
  levelpattern:
    boot001: "%clr(%-5level){%level_color}: %msg%n"
